import {
  LayoutDashboard,
  Settings,
  Box,
  Users,
  UserCog,
  Building2,
  List,
  ListTree,
  Menu as MenuIcon,
  FileText,
  Table2,
  BarChart3,
  ShieldCheck,
  Database,
  Palette,
  Image as ImageIcon,
  Workflow,
  Languages,
  Mail,
  Lightbulb,
  Cog,
  Folder,
  Layers,
  Tag,
  KeyRound,
  DatabaseBackup,
  Package,
  Ruler,
  Factory,
  Percent,
  // Status / approval + general-purpose glyphs
  CheckCircle2,
  XCircle,
  Clock,
  Hourglass,
  Send,
  Eye,
  ThumbsUp,
  ThumbsDown,
  Ban,
  BadgeCheck,
  AlertTriangle,
  AlertCircle,
  CircleDashed,
  CircleDot,
  Flag,
  Bell,
  Inbox,
  ClipboardList,
  ClipboardCheck,
  GitBranch,
  ArrowRight,
  FileCheck,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  Loader2,
  Handshake,
  Stamp,
  ShoppingCart,
  ShoppingBag,
  Truck,
  Boxes,
  Warehouse,
  Wallet,
  DollarSign,
  CreditCard,
  Calendar,
  Star,
  Bookmark,
  Heart,
  Zap,
  Home,
  Phone,
  MapPin,
  UserCheck,
  Briefcase,
  Utensils,
  // Accounts — the chart, and the vouchers written against it
  HandCoins,
  Banknote,
  Landmark,
  Receipt,
  PencilLine,
  ArrowLeftRight,
  FileMinus,
  FilePlus,
  FolderTree,
  BookOpen,
  BookOpenCheck,
  Network,
  type LucideIcon,
} from 'lucide-react';

// Map common icon names (lucide-style or fontawesome-style "fa fa-*") to lucide components.
const MAP: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  'layout-dashboard': LayoutDashboard,
  settings: Settings,
  cog: Cog,
  cogs: Settings,
  'fa-cogs': Settings,
  'fa-cog': Settings,
  box: Box,
  cube: Box,
  'fa-cube': Box,
  object: Box,
  objects: Box,
  users: Users,
  'fa-users': Users,
  user: Users,
  usercog: UserCog,
  'user-cog': UserCog,
  group: Users,
  groups: Users,
  building: Building2,
  building2: Building2,
  'building-2': Building2,
  company: Building2,
  'fa-building': Building2,
  list: List,
  'fa-list': List,
  listtree: ListTree,
  lookup: List,
  lookups: List,
  menu: MenuIcon,
  'fa-bars': MenuIcon,
  file: FileText,
  'file-text': FileText,
  form: FileText,
  forms: FileText,
  table: Table2,
  table2: Table2,
  tables: Table2,
  report: BarChart3,
  reports: BarChart3,
  chart: BarChart3,
  shield: ShieldCheck,
  shieldcheck: ShieldCheck,
  security: ShieldCheck,
  database: Database,
  'database-backup': DatabaseBackup,
  backup: DatabaseBackup,
  palette: Palette,
  theme: Palette,
  image: ImageIcon,
  workflow: Workflow,
  language: Languages,
  languages: Languages,
  mail: Mail,
  email: Mail,
  lightbulb: Lightbulb,
  thought: Lightbulb,
  folder: Folder,
  layers: Layers,
  module: Layers,
  modules: Layers,
  tag: Tag,
  key: KeyRound,
  package: Package,
  inventory: Package,
  ruler: Ruler,
  unit: Ruler,
  units: Ruler,
  factory: Factory,
  percent: Percent,
  tax: Percent,
  hsn: Percent,
  // status / approval + general
  'check-circle': CheckCircle2,
  'check-circle-2': CheckCircle2,
  approved: CheckCircle2,
  'x-circle': XCircle,
  rejected: XCircle,
  clock: Clock,
  pending: Clock,
  hourglass: Hourglass,
  waiting: Hourglass,
  send: Send,
  forward: Send,
  forwarded: Send,
  eye: Eye,
  review: Eye,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  ban: Ban,
  cancel: Ban,
  cancelled: Ban,
  'badge-check': BadgeCheck,
  'alert-triangle': AlertTriangle,
  warning: AlertTriangle,
  'alert-circle': AlertCircle,
  alert: AlertCircle,
  'circle-dashed': CircleDashed,
  draft: CircleDashed,
  'circle-dot': CircleDot,
  progress: CircleDot,
  'in-progress': CircleDot,
  flag: Flag,
  bell: Bell,
  notify: Bell,
  inbox: Inbox,
  'clipboard-list': ClipboardList,
  'clipboard-check': ClipboardCheck,
  'git-branch': GitBranch,
  branch: GitBranch,
  route: GitBranch,
  'arrow-right': ArrowRight,
  'file-check': FileCheck,
  'play-circle': PlayCircle,
  start: PlayCircle,
  'pause-circle': PauseCircle,
  hold: PauseCircle,
  'rotate-ccw': RotateCcw,
  revert: RotateCcw,
  loader: Loader2,
  processing: Loader2,
  handshake: Handshake,
  deal: Handshake,
  stamp: Stamp,
  approve: Stamp,
  'shopping-cart': ShoppingCart,
  cart: ShoppingCart,
  'shopping-bag': ShoppingBag,
  truck: Truck,
  delivery: Truck,
  boxes: Boxes,
  warehouse: Warehouse,
  wallet: Wallet,
  currency: Wallet,
  'dollar-sign': DollarSign,
  dollar: DollarSign,
  'credit-card': CreditCard,
  calendar: Calendar,
  star: Star,
  bookmark: Bookmark,
  heart: Heart,
  zap: Zap,
  home: Home,
  phone: Phone,
  'map-pin': MapPin,
  location: MapPin,
  'user-check': UserCheck,
  briefcase: Briefcase,
  utensils: Utensils,
  mess: Utensils,
  canteen: Utensils,
  // Accounts. Unmapped names fall back to a plain folder, which is why every
  // screen in this module used to look alike in the sidebar.
  'hand-coins': HandCoins,
  banknote: Banknote,
  cash: Banknote,
  landmark: Landmark,
  bank: Landmark,
  receipt: Receipt,
  invoice: Receipt,
  'pencil-line': PencilLine,
  journal: PencilLine,
  'arrow-left-right': ArrowLeftRight,
  contra: ArrowLeftRight,
  'file-minus': FileMinus,
  'file-plus': FilePlus,
  'folder-tree': FolderTree,
  'book-open': BookOpen,
  ledger: BookOpen,
  'book-open-check': BookOpenCheck,
  'list-tree': ListTree,
  network: Network,
};

export function resolveIcon(name?: string | null): LucideIcon {
  if (!name) return Folder;
  const key = name
    .toLowerCase()
    .replace(/^fa\s+/, '')
    .replace(/^fa-/, '')
    .trim();
  return MAP[key] || MAP[name.toLowerCase()] || Folder;
}

/**
 * Curated list of selectable icons for the icon picker. The `name` is what gets
 * stored in the DB (and resolved back via {@link resolveIcon}); `label` is the
 * human-readable text shown next to the glyph.
 */
export interface IconOption {
  name: string;
  label: string;
  Icon: LucideIcon;
}

export const ICON_OPTIONS: IconOption[] = [
  { name: 'dashboard', label: 'Dashboard', Icon: LayoutDashboard },
  { name: 'settings', label: 'Settings', Icon: Settings },
  { name: 'cog', label: 'Cog', Icon: Cog },
  { name: 'box', label: 'Box / Object', Icon: Box },
  { name: 'users', label: 'Users', Icon: Users },
  { name: 'user-cog', label: 'User Settings', Icon: UserCog },
  { name: 'building2', label: 'Company / Building', Icon: Building2 },
  { name: 'list', label: 'List', Icon: List },
  { name: 'listtree', label: 'List Tree', Icon: ListTree },
  { name: 'menu', label: 'Menu', Icon: MenuIcon },
  { name: 'file-text', label: 'Form / File', Icon: FileText },
  { name: 'table2', label: 'Table', Icon: Table2 },
  { name: 'report', label: 'Report / Chart', Icon: BarChart3 },
  { name: 'shieldcheck', label: 'Security', Icon: ShieldCheck },
  { name: 'database', label: 'Database', Icon: Database },
  { name: 'database-backup', label: 'Backup / Restore', Icon: DatabaseBackup },
  { name: 'package', label: 'Package / Inventory', Icon: Package },
  { name: 'ruler', label: 'Ruler / Unit', Icon: Ruler },
  { name: 'factory', label: 'Factory / Production', Icon: Factory },
  { name: 'percent', label: 'Percent / Tax', Icon: Percent },
  { name: 'palette', label: 'Theme / Palette', Icon: Palette },
  { name: 'image', label: 'Image', Icon: ImageIcon },
  { name: 'workflow', label: 'Workflow', Icon: Workflow },
  { name: 'languages', label: 'Languages', Icon: Languages },
  { name: 'mail', label: 'Mail', Icon: Mail },
  { name: 'lightbulb', label: 'Lightbulb', Icon: Lightbulb },
  { name: 'folder', label: 'Folder', Icon: Folder },
  { name: 'layers', label: 'Layers / Module', Icon: Layers },
  { name: 'tag', label: 'Tag', Icon: Tag },
  { name: 'key', label: 'Key', Icon: KeyRound },
  // Status / approval
  { name: 'check-circle', label: 'Approved / Check', Icon: CheckCircle2 },
  { name: 'badge-check', label: 'Verified / Badge', Icon: BadgeCheck },
  { name: 'stamp', label: 'Approve / Stamp', Icon: Stamp },
  { name: 'x-circle', label: 'Rejected / X', Icon: XCircle },
  { name: 'ban', label: 'Cancelled / Ban', Icon: Ban },
  { name: 'clock', label: 'Pending / Clock', Icon: Clock },
  { name: 'hourglass', label: 'Waiting / Hourglass', Icon: Hourglass },
  { name: 'circle-dashed', label: 'Draft', Icon: CircleDashed },
  { name: 'circle-dot', label: 'In progress', Icon: CircleDot },
  { name: 'loader', label: 'Processing', Icon: Loader2 },
  { name: 'send', label: 'Forward / Send', Icon: Send },
  { name: 'arrow-right', label: 'Next / Arrow', Icon: ArrowRight },
  { name: 'git-branch', label: 'Route / Branch', Icon: GitBranch },
  { name: 'eye', label: 'Review / Eye', Icon: Eye },
  { name: 'thumbs-up', label: 'Thumbs up', Icon: ThumbsUp },
  { name: 'thumbs-down', label: 'Thumbs down', Icon: ThumbsDown },
  { name: 'file-check', label: 'File check', Icon: FileCheck },
  { name: 'clipboard-list', label: 'Clipboard list', Icon: ClipboardList },
  { name: 'clipboard-check', label: 'Clipboard check', Icon: ClipboardCheck },
  { name: 'handshake', label: 'Deal / Handshake', Icon: Handshake },
  { name: 'flag', label: 'Flag', Icon: Flag },
  { name: 'bell', label: 'Notify / Bell', Icon: Bell },
  { name: 'inbox', label: 'Inbox', Icon: Inbox },
  { name: 'alert-triangle', label: 'Warning', Icon: AlertTriangle },
  { name: 'alert-circle', label: 'Alert', Icon: AlertCircle },
  { name: 'play-circle', label: 'Start', Icon: PlayCircle },
  { name: 'pause-circle', label: 'Hold', Icon: PauseCircle },
  { name: 'rotate-ccw', label: 'Revert', Icon: RotateCcw },
  // Commerce / general
  { name: 'shopping-cart', label: 'Cart / Order', Icon: ShoppingCart },
  { name: 'shopping-bag', label: 'Bag', Icon: ShoppingBag },
  { name: 'truck', label: 'Delivery / Truck', Icon: Truck },
  { name: 'boxes', label: 'Boxes', Icon: Boxes },
  { name: 'warehouse', label: 'Warehouse', Icon: Warehouse },
  { name: 'wallet', label: 'Wallet / Currency', Icon: Wallet },
  { name: 'dollar-sign', label: 'Dollar', Icon: DollarSign },
  { name: 'credit-card', label: 'Credit card', Icon: CreditCard },
  { name: 'calendar', label: 'Calendar', Icon: Calendar },
  { name: 'briefcase', label: 'Briefcase', Icon: Briefcase },
  { name: 'utensils', label: 'Mess / Canteen', Icon: Utensils },
  { name: 'user-check', label: 'User check', Icon: UserCheck },
  { name: 'star', label: 'Star', Icon: Star },
  { name: 'bookmark', label: 'Bookmark', Icon: Bookmark },
  { name: 'heart', label: 'Heart', Icon: Heart },
  { name: 'zap', label: 'Zap / Fast', Icon: Zap },
  { name: 'home', label: 'Home', Icon: Home },
  { name: 'phone', label: 'Phone', Icon: Phone },
  { name: 'map-pin', label: 'Location', Icon: MapPin },
];
